<a href="https://colab.research.google.com/github/SeunghyoKu/Algorithms/blob/master/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---

## Assignment #1


* Release date: 2019/09/23
* Due date: **2019/09/30 00:00** (will not accept late submission)
* Submittion format: notebook file which can be executed in Colab environment
* Weighting: 5% (total 50 pts)

1. **(10pts)** Calculate `np.dot(x, rotation)` and explain how this calculation is performed.

```python
  import numpy as np

  x = np.array([2, 0])
  rotation = np.array([ [0, -1],
                        [1,  0] ])
```

In [0]:
import numpy as np

x = np.array([2, 0])
rotation = np.array([ [0, -1],
                      [1,  0] ])
np.dot(x, rotation)  

array([ 0, -2])

**Answer)** numpy.dot shows dot product of arrays. 
The result shows 1D array, [0, -2] that came from `[2*0+0*1, 2*-1+0*0].`

---


2. **(10pts)** Suppose we have the following 2D tensor (i.e., a matrix). How to rearrange its values into 1D tensor (i.e., a vector) in a column major order?
```python
x = np.array([[1,  2,  3,  4],
                 [5,  6,  7,  8],
                 [9, 10, 11, 12]])
```

In [0]:
x = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

np.ravel(x, order = "F")

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

**Answer)** Because the problem asks that rearrange the 2D tensor to 1D tensor in a column major order, I used ravel function order by "F". It means that it follows Fortan method.

---


3. **(10pts)** Compute a transpose of the matrix `x` in Problem 2 by using only `np.reshape` function.

In [0]:
reshaped_x = x.reshape(12, order = "F")
reshaped_x.reshape(4,3)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

**Answer)** I used reshape function twice. The transpose of the matrix means that columns and rows are changed. There is transpose function in Python numpy api, however there was a restriction of using only reshape function to make transpose of the matrix. After testing several times, I realized that using reshape function for one time, is not able to transpose the matrix. I found that, reshaping with number of elements makes it storing elements in the sequence of columns. So, after the revision, I tried it to change to 4 arrays.

---

4. **(20pts)** Given any random matrices, compute the element-wise multiplication using a naive Python implementation and Numpy built-in function respectively. Compare the wall-clock times of these implementations as the size of matrices increases.


In [0]:
# Making random matrice with size (10,10)
# I set the size arbitrarily
# dd

from time import process_time

x = np.random.randint(0, 10, size = (10, 10))
y = np.random.randint(0, 10, size = (10, 10))

print("x:",x)
print("y:",y)

x: [[7 1 5 1 0 7 4 7 3 1]
 [2 5 6 6 0 8 4 7 7 5]
 [0 7 7 4 0 2 9 1 1 8]
 [1 1 3 8 4 1 0 3 8 1]
 [5 6 2 0 7 2 0 3 0 6]
 [7 8 7 9 6 4 6 6 7 4]
 [8 3 1 0 0 0 6 2 6 7]
 [9 0 4 5 8 0 9 3 9 4]
 [7 1 8 2 6 4 9 4 9 3]
 [5 6 0 5 9 8 4 5 5 5]]
y: [[6 9 9 9 1 4 7 2 5 7]
 [7 4 7 0 8 1 6 3 8 1]
 [8 1 3 3 7 8 8 1 6 0]
 [3 7 7 7 3 9 9 5 8 9]
 [2 5 0 0 4 4 3 6 1 9]
 [4 7 1 1 6 5 7 3 4 1]
 [5 9 2 5 8 9 2 7 9 3]
 [3 4 5 1 2 5 8 8 7 0]
 [9 5 8 2 3 8 5 2 3 6]
 [7 5 9 6 7 4 7 6 7 2]]


In [0]:
# Numpy built-in function
t = process_time()

print("x * y:", x * y)

elapsed_time1 = process_time() - t
print("elapsed time:",elapsed_time1)

x * y: [[42  9 45  9  0 28 28 14 15  7]
 [14 20 42  0  0  8 24 21 56  5]
 [ 0  7 21 12  0 16 72  1  6  0]
 [ 3  7 21 56 12  9  0 15 64  9]
 [10 30  0  0 28  8  0 18  0 54]
 [28 56  7  9 36 20 42 18 28  4]
 [40 27  2  0  0  0 12 14 54 21]
 [27  0 20  5 16  0 72 24 63  0]
 [63  5 64  4 18 32 45  8 27 18]
 [35 30  0 30 63 32 28 30 35 10]]
elapsed time: 0.0016836019999999507


In [0]:
# Naive Python implementation
t = process_time()

multi = np.zeros((10,10))

for i in range(len(x)):
  for j in range(len(x[0])):
    multi[i][j] = x[i][j] * y[i][j]

print("x * y:",multi)

elapsed_time2 = process_time() - t
print("elapsed time:",elapsed_time2)

x * y: [[42.  9. 45.  9.  0. 28. 28. 14. 15.  7.]
 [14. 20. 42.  0.  0.  8. 24. 21. 56.  5.]
 [ 0.  7. 21. 12.  0. 16. 72.  1.  6.  0.]
 [ 3.  7. 21. 56. 12.  9.  0. 15. 64.  9.]
 [10. 30.  0.  0. 28.  8.  0. 18.  0. 54.]
 [28. 56.  7.  9. 36. 20. 42. 18. 28.  4.]
 [40. 27.  2.  0.  0.  0. 12. 14. 54. 21.]
 [27.  0. 20.  5. 16.  0. 72. 24. 63.  0.]
 [63.  5. 64.  4. 18. 32. 45.  8. 27. 18.]
 [35. 30.  0. 30. 63. 32. 28. 30. 35. 10.]]
elapsed time: 0.003810073000000358


In [0]:
print("The difference of process time between numpy function and naive python is",elapsed_time1 - elapsed_time2)

The difference of process time between numpy function and naive python is -0.0021264710000004072


When I made only 10 by 10 matrix to multiply it takes time of 0.0016836019999999507, 0.003810073000000358 respectively. Its diffence was 0.0021264710000004072.


When I made only 100 by 100 matrix to multiply it takes time of 0.0026650070000000525, 0.019183219000000307 respectively. Its difference was 0.016518212000000254.

I found that to compute element-wise multiplication it is better to use Numpy built-in function than naive Python implemention. It is more faster and simpler, and the efficiency was noticeable when the size became bigger. I think that if we don't have to compare a large size of dataset, it maybe not bad to use naive Python.